### ISSUE TITLE
Missing Template Directory

### ISSUE THREAD

**Issue by StorminGorman** [StorminGorman/ngen#1]
after doing a global install and trying to run `ngen create component some_component` I get an exception:

```
➜  src git:(master) ✗ ngen create component angular_carousel
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/briangorman/.pub-cache/global_packages/ngen/lib/templates/component.scss-template' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:592:18)
#4      ComponentGenerator.createFile (package:ngen/generator/component_generator.dart:25:29)
#5      ComponentGenerator.generate (package:ngen/generator/component_generator.dart:19:5)
<asynchronous suspension>
#6      CreateComponentCommand.run (package:ngen/commands/create_component_command.dart:19:17)
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     NGen.execute (package:ngen/ngen.dart:13:9)
#12     main (file:///Users/briangorman/.pub-cache/hosted/pub.dartlang.org/ngen-0.0.1/bin/main.dart:4:19)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by StorminGorman** [comment]
Fixed: https://github.com/StorminGorman/ngen/commit/0ab85c15da942681bea01e7268e6434ed9ea2671

Had to harcode the template strings in the dart code so they would come along with the compiled executable when `pub global activate ngen` .. apparently what comes down when you do a `pub global activate` is just the executable and a pubspec.lock?
